# ┌─────────────────────────────────────────────────────────────────────────────────────────+
# │ [ ArcInventorySaveTicket 콘피그 파일입니다. ]
# │ [ 불필요한 메시지는 지우거나 해당 라인 앞에 '#'을 붇여서 주석 처리해주세요. ]
# │
# │ - 아르카디아 디스코드 : https://discord.gg/NanAFkRdww
# │ - 아르카디아 위키 : https://pixtore.gitbook.io/wiki/
# └─────────────────────────────────────────────────────────────────────────────────────────+

# ┌─────────────────────────────────────────────────────────────────────────────────────────+
# │
# │ [💬][ 메시지 설정 ]
# │
# └─────────────────────────────────────────────────────────────────────────────────────────+
message:
  normal:
    # 접두사
    prefix: "&6&l[ 인벤세이브권 ] &r"

    # config를 리로드 했을 때 출력됨
    reload_config: "&a콘피그를 리로드했습니다."

  error:
    # 콘솔로 명령어를 입력했을 때 출력됨
    player_only: "&c플레이어만 입력이 가능한 커맨드입니다."

    # 권한이 없을 때 출력됨
    no_permission: "&c명령어를 사용할 권한이 없습니다."

    # 잘못된 명령어를 입력했을 때 출력됨
    wrong_command: "&c잘못된 명령어입니다."

    # 플레이어가 잘못된 명령어를 입력했을 때 출력됨
    player_wrong_command: "&r올바른 사용법: /인벤세이브권"

  main:
    # 잔액이 부족할 때 출력됨
    air_item_in_hand: "&c손에 아이템을 들고 명령어를 입력해주세요."

    # 인벤세이브권을 생성할 때 출력됨
    create_ticket: "&a해당 아이템을 인벤세이브권으로 설정하였습니다."

    # 인벤세이브권을 발급할 때 출력됨
    get_ticket: "&f생성한 인벤세이브권을 발급하였습니다."